apiVersion: v1
kind: Service
metadata:
  name: kubernetes-configmap-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: kubernetes-configmap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-configmap
  labels:
    app: kubernetes-configmap
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-configmap
  template:
    metadata:
      labels:
        app: kubernetes-configmap
    spec:
      containers:
      - name: kubernetes-configmap
        image: nginx
        ports:
        - containerPort: 8080
