---
- name: Install and start Nginx
  hosts:  localhost
  remote_user: ubuntu
  become: true
  
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: true
