- name: Install and start Nginx
  hosts: all
  remote_user: ubuntu
  become: yes

  tasks:
    - name: update
      apt:
        update_cache: yes

    - name: install apache2
      apt:
        name: apache2
        state: latest

    - name: start apache2
      service:
        name: apache2
        state: started
        enabled: yes
      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted
